[Launch]
ProgramExecutable64=DuckDuckGoBrowser\DuckDuckGo.exe
DirectoryMoveOK=yes
SupportsUNC=yes
;As of July 8, 2026, there is no MinOS=10 or anything like that so it is better to specify in the 'readme'

[Activate]
Registry=true
Java=find

[Environment]
SET __COMPAT_LAYER=

[RegistryKeys]
DDGBrowser=HKCU\SOFTWARE\DuckDuckGo
DDGBrowserEdgeWebView=HKCU\SOFTWARE\Microsoft\EdgeWebView
DDGBrowserAppUserModelId=HKCU\SOFTWARE\Classes\AppUserModelId
DDGBrowserAppCompatFlags=HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store
DDGBrowserFeatureUsageAppSwitched=HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched
DDGBrowserSearchJumplistData=HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search\JumplistData

[RegistryCleanupIfEmpty]
1=HKCU\SOFTWARE\DuckDuckGo
2=HKCU\SOFTWARE\Microsoft\EdgeWebView
3=HKCU\SOFTWARE\Classes\AppUserModelId
4=HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store
5=HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched
6=HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search\JumplistData

[DirectoriesMove]
breadcrumb=%ALLUSERSAPPDATA%\Microsoft\NetFramework\BreadcrumbStore
profile=%LOCALAPPDATA%\DuckDuckGo
profilewebviewpublished=%LOCALAPPDATA%\DuckDuckGo.WebView.Published
localtemp=%LOCALAPPDATA%\Local\Temp\DuckDuckGo
desktop=%USERPROFILE%\Desktop

[DirectoriesCleanupForce]
1=%ALLUSERSAPPDATA%\Microsoft\NetFramework\BreadcrumbStore

[DirectoriesCleanupIfEmpty]
1=%LOCALAPPDATA%\DuckDuckGo
2=%LOCALAPPDATA%\DuckDuckGo.WebView.Published
3=%LOCALAPPDATA%\Local\Temp\DuckDuckGo

[Language]
Base=%PortableApps.comLocaleName%

[LanguageStrings]
Arabic=49102d
Bulgarian=49103d
Catalan=49105d
SimpChinese=49107d
TradChinese=49108d
Czech=49106d
Danish=49109d
Dutch=49110d
English=49101d
Estonian=49112d
Finnish=49113d
French=49114d
Galician=49115d
German=49116d
Greek=49117d
Hebrew=49132d
Hungarian=49104d
Irish=49136d
Italian=49118d
Japanese=49133d
Korean=49119d
Latvian=49120d
Lithuanian=49121d
Norwegian=49122d
Polish=49123d
Portuguese=49124d
PortugueseBR=49125d
Romanian=49126d
Russian=49127d
Serbian=49138d
Slovenian=49128d
Spanish=49129d
Swedish=49130d
Thai=49134d
Turkish=49131d
Valencian=49135d